# Generated by Django 3.2.3 on 2021-06-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('enc_file', models.FileField(upload_to='')),
                ('key', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
