# Generated by Django 3.2.3 on 2021-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_encryption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='enc_file',
            field=models.FileField(upload_to='encoded'),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
