# Generated by Django 3.2.3 on 2021-06-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_encryption', '0002_auto_20210611_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='enc_file',
            field=models.FileField(blank=True, null=True, upload_to='encoded'),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
