# Generated by Django 3.2.3 on 2021-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_encryption', '0003_auto_20210611_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
