# Generated by Django 3.2.3 on 2021-06-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_encryption', '0004_alter_encryption_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encryption',
        ),
    ]
